Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/anaconda3/envs/pse-ml/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# understand tensors
scalar = torch.tensor(7)
print(scalar)
print(scalar.shape)
print(scalar.ndim)
print(type(scalar.item()))
print(scalar.item())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;66;03m# understand tensors[39;00m
[0;32m----> 2[0m scalar [38;5;241m=[39m [43mtorch[49m[38;5;241m.[39mtensor([38;5;241m7[39m)
[1;32m      3[0m [38;5;28mprint[39m(scalar)
[1;32m      4[0m [38;5;28mprint[39m(scalar[38;5;241m.[39mshape)

[0;31mNameError[0m: name 'torch' is not defined

